//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tx_orders
    {
        public int ID { get; set; }
        public string phone { get; set; }
        public string pointA { get; set; }
        public string pointB { get; set; }
        public int kilometers { get; set; }
        public decimal price { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
        public string driver { get; set; }
        public string dispatcher { get; set; }
    }
}
